### ISSUE TITLE
All technology outputs for financial models to be analysis period long or single values

### ISSUE THREAD

**Issue by sjanzou** [NREL/ssc#1006]
The fuel cell model has fuelcell_dispatched output of length analysis period + 1 and is used for production o and m costs in financial models.

The convention for all technology model outputs that are used in financial models is:
1. analysis period for lifetime mode
2. single values for single year technology compute modules

See discussion at https://github.com/NREL/SAM/issues/659#issuecomment-1464105549 for more details

**Comment by janinefreeman** [comment]
@sjanzou has this been fixed already in the hybrids work, by chance?

**Comment by sjanzou** [comment]
> @sjanzou has this been fixed already in the hybrids work, by chance?

Not yet fixed in hybrid branch 
<img width="972" alt="image" src="https://github.com/NREL/ssc/assets/6498311/005dda00-b5d2-4ef4-9efe-123042e6e864">
