### ISSUE TITLE
PV Non-annual simulations starting with Hour !=0 fail for pvsamv1 and pvwattsv8

### ISSUE THREAD

**Issue by cpaulgilman** [NREL/ssc#1036]
The SSC `util::hour_of_year()` function breaks non-annual simulations that use `solar_resource_data` as input instead of `solar_resource_file` when the weather data is for a period less than one year and starts at Hour !=0.

See https://github.com/NREL/pysam/issues/156 and https://github.com/NREL/ssc/pull/830.

Test files for SDKTool with SSC library version > 280 (uses `adjust_constant` intead of `adjust:constant`):

[pv-non-annual-simulation-with-non-zero-start-hour.zip](https://github.com/NREL/ssc/files/12044963/pv-non-annual-simulation-with-non-zero-start-hour.zip)

For example, see this assignment of the `ac` output variable in pvwattsv8: https://github.com/NREL/ssc/blob/c72cfab5c831b131e136cb2fc48bf10c58304031/ssc/cmod_pvwattsv8.cpp#L1361C21-L1361C21

This needs to be fixed for pvsamv1 and pvwattsv8.

**Comment by janinefreeman** [comment]
Confirmed that pvsamv1 and pvwattsv8 can both run non-annual simulations with starting hour !=0, added a test of this in #1065
