### ISSUE TITLE
Hybrids: fuel cell and battery report full system energy in annual energy outputs

### ISSUE THREAD

**Issue by brtietz** [NREL/ssc#1056]
**Describe the bug**
Battery and fuel cell technologies are adding up "gen" in order to report annual energy values. However, by this point "gen" already includes the sum of the generators, so this is overreporting the discharge energy for these systems. This fuel cell output is currently reported in Paul's metrics table.

**To Reproduce**
1. Run a hybrids case
2. Look at the battery annual energy
3. See that it is the sum of the generators

**Expected behavior**
The PV+Battery hybrid puts battery annual discharge energy in the cash flow, a similar approach could be taken for hybrids. Would need to find an analogous output for fuel cells. 

**Screenshots**
![image](https://github.com/NREL/ssc/assets/5530592/510c9e55-6c76-4f9b-b95d-8d8efa4d2c29)

**Comment by janinefreeman** [comment]
Decided at 10/25/23 working meeting:
"Year 1 Generation by Subsystem" metrics table:
Fuel cell should report dispatched energy
Battery energy line should be removed
