### ISSUE TITLE
cmod_hybrid needs to propagate errors from lower level cmods

### ISSUE THREAD

**Issue by brtietz** [NREL/ssc#1105]
Errors thrown in lower level cmods are ignored, and the error shown to the user is the next arbitrary error from cmod_hybrid.

Check the error status from each cmod called in cmod_hybrid and propagate notices, warnings, and errors to the user.

**Comment by dguittet** [comment]
See `ssc_module_exec_with_error` in https://github.com/NREL/ssc/pull/1091/commits/a68f4138fac5e26dd008eac1235958d7cd178af8#diff-0bb15765ddde12ea78e017fc6256d566c64c615d9b31a135366ff72277e0c80d
