### ISSUE TITLE
Building with with LLVM's libc++ (and general cmake configuration)

### ISSUE THREAD

**Issue by jmarrec** [NREL/ssc#1118]
**Describe the bug**

This should never be done like this:

https://github.com/NREL/ssc/blob/9d76d0c8384f482bf803cd133dca26b720cd2b88/ssc/CMakeLists.txt#L253

Please remove the `lstdc++`.  Side note but the rest is also supoptimal:

```diff
-target_link_libraries(ssc -lpthread -lm -ldl -lstdc++)
+find_package(Threads REQUIRED)
+target_link_libraries(ssc PUBLIC Threads::Threads ${CMAKE_DL_LIBS}) 
+find_library(MATH_LIBRARY m)
+if(MATH_LIBRARY)
+    target_link_libraries(ssc PUBLIC ${MATH_LIBRARY})
+endif()
```

[CMAKE_DL_LIBS](https://cmake.org/cmake/help/latest/variable/CMAKE_DL_LIBS.html)

That bit below defines CMAKE_CXX_STANDARD twice (and it does it globally... which is frowned upon). The CMAKE_C_COMPILER block is super strange and should be removed. The `project`command should use the `LANGUAGES CXX` which would take care of linking to a C++ std lib, and defining the C/CXX compilers as needed.

https://github.com/NREL/ssc/blob/9d76d0c8384f482bf803cd133dca26b720cd2b88/CMakeLists.txt#L28-L48

Generally speaking, the project could benefit from a deep cleaning and modernization of the CMake config (eg: avoid polluting the global space and use target specific compilation flags). I know that's probably not a priority and not a sexy task, just saying.

**Additional context**

I noticed some issues while trying to build EnergyPlus with clang-17 on macOS M1.

**Comment by brtietz** [comment]
Thank you for flagging this! We have some pending CMakeLists changes coming with https://github.com/NREL/ssc/pull/1035, we'll see if we can bundle these fixes in with those changes.
