### ISSUE TITLE
lib_irradproc.cpp calls exit()

### ISSUE THREAD

**Issue by bje-** [NREL/ssc#112]
This library code calls `exit(1)` which seems to be wrong to me.

https://github.com/NREL/ssc/blob/c49793e358facb3beb047c1183e0b9d0c1a6ff69/shared/lib_irradproc.cpp#L674 

Won't this give users the impression that SAM has crashed?

**Comment by nickdiorio** [comment]
I believe this line is currently commented out, but that comment block can be removed.  You are correct that is not desired behavior.

**Comment by bje-** [comment]
Oh, so it is. My fault for using `grep` in haste. :-) I will remove the block in a future patch, thanks.
