### ISSUE TITLE
Allen model not working when weather file has no DNI

### ISSUE THREAD

**Issue by mjprilliman** [NREL/ssc#1123]
**Describe the bug**
Allen method is using the weather file DNI in calculation, is giving erroneous results without warning when there is no DNI in the weather file. 

**Expected behavior**
Either use decomposed DNI in calculation when no weather file DNI is provided or error out of the simulation with an appropriate error message. 

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by cpaulgilman** [comment]
Note issue with weather files with missing irradiance data: https://github.com/NREL/SAM/issues/1685
