### ISSUE TITLE
Battery retail rates fails with hourly dispatch and TOU demand charges

### ISSUE THREAD

**Issue by brtietz** [NREL/ssc#1151]
**Describe the bug**
It appears https://github.com/NREL/ssc/pull/1135/files added a new bug that shows up in the default SAM case. It looks like an uninitialized memory or other overrun issue. Turning off the demand charges solves the issue.

**To Reproduce**
1. Open a PV-Battery commercial case
2. Change the battery dispatch to retail rates
3. Run the simulation

**Expected behavior**
Retail rates dispatch should run this configuration of rates.

**Screenshots**
Example output:

![image](https://github.com/NREL/ssc/assets/5530592/af6e0a50-85d1-41a9-a5ac-96289d4a5f81)

**Desktop (please complete the following information):**
 - Version 2023.12.17r1

**Comment by cpaulgilman** [comment]
My review of #1135 missed this. Perhaps an additional test before approving PRs for for battery dispatch and utility rate code changes should be to run the "default" case for each battery dispatch option to check for simulation errors.

**Comment by brtietz** [comment]
This was fixed in https://github.com/NREL/ssc/pull/1152
