### ISSUE TITLE
Monthly AC energy label in IPH technologies

### ISSUE THREAD

**Issue by mjprilliman** [NREL/ssc#1255]
**Describe the bug**
-For IPH singleowner configs, monthly_energy gets renamed to AC units for use in hybrid O&M calculations. Update vartable handling to not have AC units in the results. Try changing monthly_energy in vtab_hybrid_fin_om to INPUT rather than INOUT

![image](https://github.com/user-attachments/assets/e907adc0-9a6a-4d63-974c-fb47d883faa0)

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by brtietz** [comment]
Fixed with https://github.com/NREL/ssc/pull/1257
