### ISSUE TITLE
Hybrid capacity-based O&M scales with DC PV capacity

### ISSUE THREAD

**Issue by mjprilliman** [NREL/ssc#1259]
**Describe the bug**
For PVWatts and Detailed PV configs, setting the hybrid capacity based O&M to 1 $/kWAC shows that the year 1 amount is $928. This equals 100 kWAC wind, + 288.050 kWAC battery, + 540 kWDC PV capacity. 

-PV should scale with AC capacity
-Should battery capacity be included in this calculation?

**Expected behavior**
-Everything should scale based off of AC

**Screenshots**

**Desktop (please complete the following information):**

**Comment by brtietz** [comment]
Fixed with https://github.com/NREL/ssc/pull/1260
