### ISSUE TITLE
Module coefficient generator 6parsolve does not work for First Solar Series 6 CdTe modules.

### ISSUE THREAD

**Issue by cpaulgilman** [NREL/ssc#129]
https://sam.nrel.gov/forum/forum-general/1929

**Comment by janinefreeman** [comment]
Fails within "solve" function in 6par_solve.h (line 466). In UI, both in released version and open source version (built today), changing celltype input to "monoSi" or "multiSi" causes it to solve correctly. In SDKtool, I can't replicate that- monoSi and multiSi both fail, built in both 32-bit and 64-bit debug.  SDKtool script follows. Still working.

	//calculate inputs
	celltype= 'monoSi';//['monoSi', 'multiSi/polySi', 'cdte', 'cis', 'cigs', 'amorphous'];
	voc = 215;
	isc = 2.63;
	
	//call 6parsolve module
	var('celltype', celltype);
	var('Vmp', 179.4);
	var('Imp', 2.37);
	var('Voc', voc);
	var('Isc', isc);
	var('alpha_isc', -0.28 * 0.01 * isc);
	var('beta_voc', 0.04 * 0.01 * voc);
	var('gamma_pmp', -0.32);
	var('Nser', 216);
	var('Tref', 25);
	result= run('6parsolve');

**Comment by janinefreeman** [comment]
With the given specifications, SAM fails to solve for 5-parameter coefficients when "cdte" is specified as the technology, but succeed when selecting "monoSi" or "multiSi". This input only affects the initial guesses for an iterative solver. More investigation needed as to the source of these initial guesses, but it would seem that current workaround of using monoSi or multiSi, even though it is a CdTe module, is a legitimate option.

**Comment by dguittet** [comment]
see comment in pull request for fix details

**Comment by cpaulgilman** [comment]
Coefficient generator is not solving for some newer modules, for example parameters from these Trina modules marked "preliminary" :  [6parsolve-convergence-issues.zip](https://github.com/NREL/ssc/files/5211782/6parsolve-convergence-issues.zip). (These are bifacial modules, solver is only considering front side of module.)

CSV file in zip files lists module parameters and initial test results. Use lk scripts to read parameters from CSV file and run 6parsolve.

Solver does work for these similar Trina modules: 
[EN_Datasheet_Duomax_Twin_DEG15HC.20II_201907.pdf](https://github.com/NREL/ssc/files/5211783/EN_Datasheet_Duomax_Twin_DEG15HC.20II_201907.pdf)
[MA_Datasheet_Vertex_DEG18MC.20(II)_2020A.pdf](https://github.com/NREL/ssc/files/5211784/MA_Datasheet_Vertex_DEG18MC.20.II._2020A.pdf)

For Solibro module in zip file, changing celltype from cigs to multiSi causes solver to solve.
