### ISSUE TITLE
Bug in subhourly EPW file reading

### ISSUE THREAD

**Issue by nickdiorio** [NREL/ssc#140]
A user has encountered problems with SAM being unable to handle subhourly EPW files. If using the PVWatts option, the simulation will misinterpret a 15-min file as hourly and only use the first 25% of the inputs. If using the Detailed PV option, the user gets an error message, and the simulation fails.

**Comment by nickdiorio** [comment]
The recommended work around for this issue in the immediate term is to convert the file to a SAM CSV file

**Comment by janinefreeman** [comment]
Proposed path forward: error out in all compute modules if EPW is subhourly, and make sure that the conversion macro to SAM CSV properly handles subhourly EPW files.

**Comment by dguittet** [comment]
Added support for subhourly EPW files and tested on 30 min file. 
https://github.com/NREL/ssc/commit/2a261a0589bcbe12fc7aae5b3ab12d1b23660a29
