### ISSUE TITLE
Documentation of pvsamv1 irrad_mode variable options appears to be incorrect.

### ISSUE THREAD

**Issue by cpaulgilman** [NREL/ssc#143]
> ...in the SDKtool UI for which value of irrad_mode is which option is incorrect. Specifically, the option 0 is not Beam+Diff, but instead Global+Beam (so the default requires global). Might be something to improve in later releases.

https://sam.nrel.gov/node/75857

**Comment by janinefreeman** [comment]
The documentation is actually correct for all irrad_mode options. Option 0 does use Beam + Diffuse, but faulty logic inside the function threw the error that "global" was still required, when in fact it was not required but not used. There was a similar problem with the "gcr" input, where it would fail as being required when in fact it was not. This error only affected the irradproc compute module (cmod_irradproc), NOT any of the other compute modules using the irradproc functions (pvsamv1, pvwatts, etc).
