### ISSUE TITLE
Calculate and report clear sky DNI 

### ISSUE THREAD

**Issue by mjwagner2** [NREL/ssc#151]
The clear-sky direct normal irradiance (DNI) profile is sometimes useful for CSP analysis. There are several models available for estimating this value, which is location dependent and can account for certain exogenous factors, such as current humidity, pressure, or seasonal effects. The goal of calculating clear-sky DNI is typically to serve as a comparison to observed DNI, and to assist in determining the fraction of DNI energy lost over each time period due to cloudiness. In this respect, clear-sky models that predict what the DNI _would have been_ had there been no cloudiness during a time period would be most useful.

The SolarPILOT code already contains several clear-sky models, taken from 
>Kistler, B.L. “A User’s Manual for DELSOL3: A Computer Code for Calculating the Optical Performance and Optimal System Design for Solar Thermal Central Receiver Plants.” Albuquerque, NM: Sandia National Laboratory, 1986.

These include:
* Meinel 
![image](https://user-images.githubusercontent.com/26658790/37775818-ee4103c2-2db1-11e8-8629-3f04264ef7e8.png)
* Hottel
![image](https://user-images.githubusercontent.com/26658790/37776061-7d988496-2db2-11e8-86f5-b93de6d4277a.png)
* Allen
![image](https://user-images.githubusercontent.com/26658790/37775889-22b06c1a-2db2-11e8-8fcd-1ebc802e7d29.png)
![image](https://user-images.githubusercontent.com/26658790/37775903-298598e4-2db2-11e8-8694-1da2c3f3c530.png)
* Moon
![image](https://user-images.githubusercontent.com/26658790/37775950-417b42be-2db2-11e8-92a9-9fef4a8a5f3a.png)

----

All of these models are fairly old, and newer options are available, e.g. the Perez & Ineichen formulation implemented in [pvlib](https://github.com/pvlib/pvlib-python).

**Comment by janinefreeman** [comment]
Mike, we've been wanting clear-sky info in the PV models as well. Maybe there's an easy way to make it available for multiple models (irradproc?) and add more info.

**Comment by mjwagner2** [comment]
That seems like a good place for it. It might be a good idea to code up a few models and allow the user to flag which should be used. I'm not sure what the best default model should be, though.

**Comment by cpaulgilman** [comment]
A user request for this feature: https://sam.nrel.gov/forum/forum-general/3410

**Comment by cpaulgilman** [comment]
This issue is partially addressed in https://github.com/NREL/SAM/pull/609.

Clear sky DHI, DNI, and GHI data is available from the NSRDB. As of this pull request, SAM downloads the clear sky data so it is available in the weather file along with the surface irradiance values. To make this more useful, we should consider having SAM's solar  models (CSP, SWH, PV) read the data and pass it through to show in results with documentation in Help explaining that the data is not used in simulations.

**Comment by mjprilliman** [comment]
@cpaulgilman @janinefreeman This is relevant again for the subhourly clipping work. I'm currently spending some time looking into potential models or options like the NSRDB. One early potential feature request: can we have clearsky irradiance values visible in the DView widget on the Resource tab.

**Comment by mjprilliman** [comment]
Closing with https://github.com/NREL/ssc/pull/1050, https://github.com/NREL/ssc/pull/1077, see https://github.com/NREL/SAM/issues/1449 for future work.
