### ISSUE TITLE
EPW files without empty line at end of file fail to run

### ISSUE THREAD

**Issue by cpaulgilman** [NREL/ssc#212]
**Describe the bug**
Weather files from the PVGIS V5 website are in EPW format, but do not have an empty line at the end of the file, and cause SAM simulations to fail.

**To Reproduce**
Download EPW files from:
http://re.jrc.ec.europa.eu/pvg_tools/en/tools.html#TMY and download an EPW file.

**For Details**
https://sam.nrel.gov/node/80512

**Comment by sjanzou** [comment]
Tested and verified working with 2018.11.11.r1 - fixed in patch branch commit a33dc6 by dguittet
