### ISSUE TITLE
mlm model doesn't output out.AOImodifier

### ISSUE THREAD

**Issue by caseyzak24** [NREL/ssc#227]
The mlm module model in lib_mlmodel.cpp does not output `out.AOIModifier`. As a result, when using the mlm module model in conjuction with `pvsamv1`, the output signals `subarray1_poa_front` and `subarray1_poa_eff` are zero.

**Comment by nickdiorio** [comment]
We can investigate adding this, though it likely won't be for a few months.  If you'd like to submit a pull request, please feel free.

**Comment by nickdiorio** [comment]
Closed with #230
