### ISSUE TITLE
mlm module model support for irradmode=3 (poa from reference cell)

### ISSUE THREAD

**Issue by caseyzak24** [NREL/ssc#229]
The mlm module model currently only considers poa components (i.e. `input.Ibeam`, `input.Idiff`, and `input.Ignd`) but will not use directly supplied user POA reference cell data.

It would be nice if the same logic found in `iec61853_module_t` were included at the beginning of `mlm_module_t`, something like:
```
if( input.radmode != 3 ){ // Skip module cover effects if using POA reference cell data 
		double S = (f_IAM_beam * input.Ibeam + f_IAM_diff * input.Idiff + groundRelfectionFraction * f_IAM_gnd * input.Ignd) * f_AM;
        }
else if(input.usePOAFromWF){ // Check if decomposed POA is required, if not use weather file POA directly
		double S = input.poaIrr;
	} 
else { // Otherwise use decomposed POA
		double S = (f_IAM_beam * input.Ibeam + f_IAM_diff * input.Idiff + groundRelfectionFraction * f_IAM_gnd * input.Ignd) * f_AM;
	}
```

**Comment by nickdiorio** [comment]
Thanks @caseyzak24, that's a good point.  When we accepted the mlm module model via pull request, it didn't fully hook up all the available options that are present in other module models.  I think we can do this later on this year, though we'd also be happy to take the code that you've posted above as a pull request if you'd like to send which may be the fastest way to get it into the `develop` branch.
