### ISSUE TITLE
Wind LandBOS: variables undefined

### ISSUE THREAD

**Issue by janinefreeman** [NREL/ssc#231]
It appears that tower_top_mass and turbine_capital_cost are currently undefined for the wind landBOS cost model in SAM. The wind team is actively working on that model this year, so hopefully when they update that model, we'll be able to implement updates/fixes in SAM as well.

**Comment by brtietz** [comment]
These variables appear to have been removed with the LandBosse earlier this year. Closing.

**Comment by dguittet** [comment]
LandBosse is currently only for utility-scale financial models. Distributed wind configurations are still using the old wind model.

**Comment by janinefreeman** [comment]
Looking at the current release of SAM, this appears to have been fixed- the variables now show up with values in the UI.
