### ISSUE TITLE
Drop 32-bit support in summer 2019

### ISSUE THREAD

**Issue by janinefreeman** [NREL/ssc#233]
In order to streamline the number of platforms that the team has to maintain, we plan to drop Windows 32-bit support for the 2019 release. We will wait to delete those folders until we are done patching the 2018.11.11 version, likely in summer 2019. If there are any major objections to this plan of action from the community, we would like to hear them.

**Comment by janinefreeman** [comment]
@sjanzou I'm under the impression this is totally complete- is that true? If so, feel free to close this issue!

**Comment by sjanzou** [comment]
Completed in CMake and build_vs2017
