### ISSUE TITLE
Apply diffuse self-shading in all racking/shade-behavior scenarios

### ISSUE THREAD

**Issue by caseyzak24** [NREL/ssc#236]
Currently diffuse self-shading in SAM is applied as shown in the following graph

![image](https://user-images.githubusercontent.com/29411281/52514304-418fb700-2bc5-11e9-8eac-002a9df2aec2.png)

where the green scenarios have it applied and the blue scenarios do not.

However, the current diffuse self-shading model, which is based on a simple 2-D unlimited sheds geometry, seems applicable as an approximation to all scenarios. In particular for backtracking SAT systems, diffuse shading becomes important due to the higher tilt angles experienced and we've seen it contribute up to a 2% loss to energy production.

**Comment by janinefreeman** [comment]
Thanks for creating the issue with all the helpful details for this, @caseyzak24 ! The SAM team agrees that diffuse self-shading should be applied in the blue scenarios as well. If you get a chance to make some improvements (or if anyone else is interested in tackling it!), let us know!

**Comment by caseyzak24** [comment]
@janinefreeman I am currently working on this issue and I think I have it implemented, just working out a few kinks. I will submit a PR when it is complete.

**Comment by janinefreeman** [comment]
Awesome! Looking forward to it! Thanks @caseyzak24 !

**Comment by janinefreeman** [comment]
Closed in 27a1793664c34b64b06d06ba055579353f4b55fc
