### ISSUE TITLE
Generic System issues with subhourly input

### ISSUE THREAD

**Issue by nickdiorio** [NREL/ssc#240]
**Describe the bug**
When subhourly generation is used for the Generic System, the model fails with:

![image](https://user-images.githubusercontent.com/5658281/53201103-60884300-35e0-11e9-904e-1e2073ae16b6.png)

This is because in the Generic model, the length of the generation is always being set to 8760 when the battery model is initialized.

**To Reproduce**
Input a subhourly generation profile in the Generic System and enable a battery.

**Comment by nickdiorio** [comment]
Submitted #239 to address this issue

**Comment by sjanzou** [comment]
Closed with commit 7cb4deae595c01ae40ed2c01646a5432c49ef9cb to patch branch
