### ISSUE TITLE
Battery calendar life model may have minor bug

### ISSUE THREAD

**Issue by nickdiorio** [NREL/ssc#247]
As reported by @cdeline, there’s a term k_cal that has a dependence of `(SOC / T) – (1/T)` .  Based on the literature, it appears this should perhaps instead be `(V_batt / T) – (V_batt_0 / T)` where `V_batt_0 = 3.6V`.  Therefore, at 100% SOC, you have a bit of a higher terminal voltage like 4.1V which accelerates this calendar degradation loss.  

Need to investigate this and confer with transportation researchers.

**Comment by janinefreeman** [comment]
Is this possibly addressed in your new lifetime model, @dguittet ? Or is this separate?

**Comment by dguittet** [comment]
No, this is an issue with the original calendar model. The new lifetime models have entirely separate equations.
