### ISSUE TITLE
Coersion to ssc_number_t results in loss of precision

### ISSUE THREAD

**Issue by nickdiorio** [NREL/ssc#252]
**Describe the bug**
It appears that when doubles are converted to `var_data` and coersed to `ssc_number_t`, there are differences in the original and output calculations.  A good example of this is to consider a very large system, and then look at the annual energy calculated within the compute module, and then the value that is returned to the user-interface.

1. In `interconnection` branch, the computed `annual_energy` is `457534758`, as seen in `cmod_grid.cpp`:
![image](https://user-images.githubusercontent.com/5658281/56221448-7dad2100-6027-11e9-82df-821d0ad829e2.png)

2. Yet, when passed to `var_data`, it gets changed, as seen in `lib_util.h`:
![image](https://user-images.githubusercontent.com/5658281/56221601-c4028000-6027-11e9-945f-285f51c65e92.png)

So, something is something strange is happening
[generic (2).zip](https://github.com/NREL/ssc/files/3085560/generic.2.zip)

**Comment by dguittet** [comment]
ssc_number_t is a float. We should consider moving to doubles to maintain the same precision as we use in calculations.

**Comment by nickdiorio** [comment]
Good point, I thought we were dynamically deciding whether `ssc_number_t` was a double or float based on the OS.  Unclear that we need to maintain as floats in today's computational age.

**Comment by nickdiorio** [comment]
We've moved `ssc_number_t` to `double`, in the `develop` branch.
