### ISSUE TITLE
Add fields for battery augmentation, O&M costs

### ISSUE THREAD

**Issue by nickdiorio** [NREL/ssc#257]
To reflect common needs in battery storage modeling, we need to add:

- Battery augmentation cost ($/kWh-yr)
- Battery O&M cost or percentage (either separately for kW or kWh components or one total)
- Battery Warranty cost (could roll into O&M or delineate as separate category).

**Comment by brtietz** [comment]
Possible overlap with https://github.com/NREL/SAM/issues/355

**Comment by brtietz** [comment]
![image](https://user-images.githubusercontent.com/5530592/132753095-05b8b24f-d271-4ae1-8a43-678aaa6e485a.png)

Closed in https://github.com/NREL/SAM/pull/653/files
