### ISSUE TITLE
Large power cycle capacities crash SAM

### ISSUE THREAD

**Issue by Matthew-Boyd** [NREL/ssc#259]
Increasing the design gross output for a trough plant power cycle to above 150 MWe, with all other values at their defaults, will cause SAM to crash.

**Comment by Matthew-Boyd** [comment]
Added additional larger pipe sizes to CSP::pipe_sched() and returned provided diameter if larger than all those available. This was needed to handle larger pipes in the SGS. Addressed in commit: 0a255587a2fd8abb5e8d0c052a447219ef878e1d

**Comment by cpaulgilman** [comment]
This also addresses the issue reported on the SAM forum: https://sam.nrel.gov/forum/forum-general/2769-physical-parabolic-trough.html
