### ISSUE TITLE
Implement transient module thermal model

### ISSUE THREAD

**Issue by janinefreeman** [NREL/ssc#261]
Finalize implementation of transient thermal module model from Sandia

**Comment by sjanzou** [comment]
Finished for SAM 2020.2.29

**Comment by cpaulgilman** [comment]
Related SSC commits:

45cb91a88a7f12b0d1f92f1522530e15ff7db296

648f9ac72eb3480f1df1aeb988110898745b8455

a42abdf669aeaf325e705ffd6b992ba8bc6d2130
