### ISSUE TITLE
Multiple HTF flow/pump groups in SGS

### ISSUE THREAD

**Issue by Matthew-Boyd** [NREL/ssc#272]
Larger CSP plants need HTF flows in the steam generator system larger than manageable pipe sizes can handle. Multiple flow paths and pump groups should be used for when the HTF flow requires single pipes larger than about 54".

**Comment by dguittet** [comment]
@Matthew-Boyd Any updates on whether this is complete and should go into a release?

**Comment by Matthew-Boyd** [comment]
@dguittet  This never became a priority for us. I'm taking this off and moving it to my private wish list.
