### ISSUE TITLE
Un-capitalized Thermal Energy Storage "TES" acronym on CSP Linear Fresnel molten salt model

### ISSUE THREAD

**Issue by kieranfung** [NREL/ssc#274]
This is located under Parasitics within the Linear Fresnel molten salt model. In the UI, it's displayed as "tes" instead of the proper form "TES" for thermal energy storage.

**Comment by nickdiorio** [comment]
@Matthew-Boyd , @tyneises , FYI

**Comment by Matthew-Boyd** [comment]
Fixed in NREL/SAM commit 520575002e13c17faafbec31e224105cfa2a8aa1
