### ISSUE TITLE
CSP Linear Fresnel direct steam - Collector and Receiver "Annulus pressure (torr)"

### ISSUE THREAD

**Issue by kieranfung** [NREL/ssc#275]
In order for SAM (Open Source) to stay consistent, "Annulus pressure (torr)" should be changed to "Annulus gas pressure (torr)". This way Linear Fresnel direct steam and Linear Fresnel molten salt will stay consistent when using the same input parameters. 

This change is located in CSP Linear Fresnel direct steam under Collector and Receiver.

**Comment by nickdiorio** [comment]
Thanks @kieranfung for submitting, @Matthew-Boyd , @tyneises , FYI

**Comment by Matthew-Boyd** [comment]
Fixed in NREL/SAM commit 086e80c925591adbcb9dbcfeda464a79453b7ead
