### ISSUE TITLE
Switch to SPA algorithm for solar position in all models

### ISSUE THREAD

**Issue by janinefreeman** [NREL/ssc#279]
We'd like to update the solar position algorithm used for all solar models to the NREL SPA algorithm. It requires temp and RH, but those could be filled with a default value if not available in the weather file. It's the newer, standard model, and is consistent with the NSRDB workflow. At the same time, we should work to better combine the CSP/PV weather file processing and sun position calculations.

**Comment by cpaulgilman** [comment]
See https://github.com/NREL/ssc/pull/1013, modifications to SPA with SG2 equations to speed up simulations.
