### ISSUE TITLE
Unittest for Battwatts

### ISSUE THREAD

**Issue by nickdiorio** [NREL/ssc#285]
Considering #284, it's apparent we need to add tests to cover BattWatts and potentially go through the model to update.

**Comment by dguittet** [comment]
added some in pull request #324

**Comment by frohro** [comment]
This would be good.  See SAM issue [239](https://github.com/NREL/SAM/issues/239) and [240](https://github.com/NREL/SAM/issues/240).

**Comment by janinefreeman** [comment]
@brtietz If you've already addressed this in your many tests, feel free to close it! Otherwise if you could add a few more for this config, that would be super helpful. Thanks!
