### ISSUE TITLE
Geothermal model uses separate analysis period

### ISSUE THREAD

**Issue by nickdiorio** [NREL/ssc#292]
In the Geothermal compute module, an input `geothermal_analysis_period` is present, and appears to be hard-coded to 30 years coming out of the SAM user interface.  It's unclear that this is required and if it is required, it may not match the financial analysis period defined on the Financial Parameters page.

**Comment by mjprilliman** [comment]
Closing as this is handled correctly in coordination with system_use_lifetime_output.
