### ISSUE TITLE
Warning for tilted, tracking, bifacial systems

### ISSUE THREAD

**Issue by janinefreeman** [NREL/ssc#364]
The bifacialvf code that we use to calculate bifacial gain in SAM may not be suited for trackers with non-zero tilt. Would like to add an additional output warning to SSC if a user tries to model this combo.

**Comment by mjprilliman** [comment]
I believe this issue has already been addressed in a previous release. Unless there is further explanation that is needed in this warning this issue can be closed. 

![image](https://user-images.githubusercontent.com/54449384/93829282-8cd7cb80-fc2a-11ea-84b3-11034791f6a9.png)

**Comment by cpaulgilman** [comment]
This requires an additional warning for when a bifacial module is used with tracking: Bifacial model is based on fixed arrays.

**Comment by cpaulgilman** [comment]
The message appears for bifacial modules with one-axis tracking regardless of the tilt angle. It should only appear when the tilt angle is not zero: https://sam.nrel.gov/forum/forum-general/3285

**Comment by cpaulgilman** [comment]
![image](https://user-images.githubusercontent.com/27711933/106070827-09d3ef80-60ba-11eb-8b96-b3df93456d1d.png)

![image](https://user-images.githubusercontent.com/27711933/106070888-253efa80-60ba-11eb-9cf0-268775cb8fcd.png)
