### ISSUE TITLE
array overrun in sam_mw_type234.cpp

### ISSUE THREAD

**Issue by bje-** [NREL/ssc#37]
Line 213 of sam_mw_type234.cpp defines an array of nine doubles:

`double m_F_wc[9];`

g++ noticed that the array is overrun on line 263:

`m_F_wc[9] = std::numeric_limits<double>::quiet_NaN();`

Filing an issue as it's not clear what the right fix is. Perhaps it is to just delete line 263?

**Comment by mjwagner2** [comment]
looks like this was created using sloppy copy paste. Fixing by iterating over all entries.
