### ISSUE TITLE
Generalize battery power flow outputs

### ISSUE THREAD

**Issue by dguittet** [NREL/ssc#383]
In the GUI, there's no standalone battery or pairing of batteries with another technology besides PV. In the SDK & PySAM, battery + wind or just battery is possible. The outputs of the battery compute module such as `pv_to_grid`, `pv_to_batt` should be changed to more general terms such as `generator_to_grid`, `generator_to_batt`.

**Comment by cpaulgilman** [comment]
In 7bcb572a02f1b3d3199431a5701eb20d34e6ca84, I changed the variable labels to refer to 'system' instead of 'pv' but did not change the variable names themselves. I'm not sure what name to use, "generator" might suggest a fuel-powered genset, but "system" might appear to include the battery.

**Comment by dguittet** [comment]
Thanks @cpaulgilman glad to know one half of this is done already.

I am also not sure what's the best nomenclature... I am remembering unresolved naming issues around `gen`. In particular how it feeds into the financial models and whether the power going to the `load` was expected or not depends on if it was BTM or FOM-- from the bug @sjanzou resolved. I think we discussed a separate output from `gen` for the case where the power going to the load has been subtracted called `system_to_grid`.

How about `plant_to_grid`? We could also discuss at the meeting.

**Comment by dguittet** [comment]
Working with @brtietz on generic-battery, we noticed it's very confusing that "System Power Generated" is both the power plant + battery since there isn't a separate output for just the power plant/pv.

I think we need to either make a new output for just the power plant/pv or a new one for when battery is included. @cpaulgilman thoughts on naming?

**Comment by cpaulgilman** [comment]
I like gen_with_storage.

**Comment by cpaulgilman** [comment]
https://github.com/NREL/ssc/commit/ce96913e5c228bb96b702211269a8d0c8efd571d fixes SAM383 not SSC 383.

**Comment by brtietz** [comment]
@dguittet - should I take this issue to solve along with https://github.com/NREL/SAM/issues/370? `gen_with_storage` is a good variable name for the "net energy delivered to the grid" variable we discussed at last week's meeting.

**Comment by dguittet** [comment]
@brtietz Yes, that would be awesome!

**Comment by brtietz** [comment]
Closed with https://github.com/NREL/ssc/commit/e96e00f476f0af3dcefe8c5f78d3157fabe66690
