### ISSUE TITLE
pvwattsv7 10x slower than pvwattsv5

### ISSUE THREAD

**Issue by dguittet** [NREL/ssc#384]
Thanks to @grantbuster for noticing that:

> For the pysam default runs, pvwattsv5 takes 70ms, pvwattsv7 takes 900 ms, and windpower takes 210 ms. This is just a small test on my local ubuntu instance.

I tested this on mac and found a 6.6x slowdown for v7. 

Need to see if it's related to the newer features in v7. Or this may be similar to a previous issue with significant slow down on linux with the windpower module which was resolved by moving a repeated mathematical operation out of the loop (which was not automatically optimized in linux).

**Comment by janinefreeman** [comment]
@dguittet Was this also merged into develop? If so, I think we can close this issue! Thanks!
