### ISSUE TITLE
Add dispatch tests for grid power target

### ISSUE THREAD

**Issue by brtietz** [NREL/ssc#469]
After we merge in the fix for https://github.com/NREL/ssc/issues/379, there will be tests for look ahead, custom and manual dispatch for behind the meter batteries. This means maintain_target is untested. Add tests with maintain_target as a dispatch option including charging and discharging under different PV and load levels.

**Comment by janinefreeman** [comment]
@brtietz I believe this dispatch method is now tested in the battery tests, isn't it?

**Comment by brtietz** [comment]
Yes! Looks like this was handled as a part of https://github.com/NREL/ssc/pull/602
