### ISSUE TITLE
Default battery thermal doesn't work for sub-hourly simulations

### ISSUE THREAD

**Issue by brtietz** [NREL/ssc#472]
**Describe the bug**
When attempting to run a detailed pv-battery simulation with a 30 minute weather file, I get the following error:

`exec fail(battery): Environment temperature input length must equal number of weather file records
Simulation pvsamv1 failed :exec fail(battery): Environment temperature input length must equal number of weather file records
`

This is with "Enter single fixed temperature" on the battery thermal page.

**To Reproduce**
1. Start a PV battery simulation
2. Select a subhourly weather file
3. Run simulation

**Expected behavior**
The default battery parameter (enter single fixed temperature) should be able to handle any weather file

**Comment by brtietz** [comment]
This is new to the 2021 release (develop), in 2020.2.29 r3 this problem does not exist.

**Comment by dguittet** [comment]
Currently in develop, `batt_room_temperature_celsius` must have length == nrec. I think this is unnecessary and could have length of 1 as well.

**Comment by brtietz** [comment]
Closed by https://github.com/NREL/SAM/pull/418
