### ISSUE TITLE
Fuel cell battery variable OM costs not calculated for production

### ISSUE THREAD

**Issue by mjprilliman** [NREL/ssc#526]
**Describe the bug**
In the Fuel Cell-PV-Battery model, the variable production cost in $/kWh is input for batteries (om_production1) and fuel cell (om_production2). These values do not appear to be multiplied by the production anywhere in the financial models before being applied in the financial metric calculations. For example in cmod_singleowner.cpp:

Initialization: 
![image](https://user-images.githubusercontent.com/54449384/106533383-4daa6880-64af-11eb-8ed3-82ac3510289a.png)

PV production costs are calculated, but not for battery or fuel cell: 
![image](https://user-images.githubusercontent.com/54449384/106533430-661a8300-64af-11eb-8b7c-2b6d60ba3533.png)

Included in operating expenses without any adjustments: 
![image](https://user-images.githubusercontent.com/54449384/106533539-9eba5c80-64af-11eb-995e-ead346c048f5.png)

Expected behavior: 
Production costs should be adjusted by multiplying by CF_energy_net or CF_energy_net_without_battery for matching units ($ rather than $/kWh).

**Comment by mjprilliman** [comment]
@cpaulgilman @sjanzou My mistake. These inputs are not available in the UI so they are likely not intended to be used. Should they be added as part of the LCOS work?

**Comment by sjanzou** [comment]
@mjprilliman, yes they should be added  but we should also clean them up and use a more descriptive naming convention.

**Comment by sjanzou** [comment]
Also, as you noted, the production (variable) o and m costs should be multiplied by an output of system generation - either kWh or a sum of the power production at a timestep multiplied by the variable cost input.

**Comment by mjprilliman** [comment]
This was fixed in #596. Closing for now
