### ISSUE TITLE
Buy all / sell all incorrectly assigns tier to inverter night time losses

### ISSUE THREAD

**Issue by brtietz** [NREL/ssc#539]
After https://github.com/NREL/ssc/pull/538, the kWh w/o system are allocated correctly for buy all / sell all when using kWh/kW rates:

![image](https://user-images.githubusercontent.com/5530592/108286383-35d91280-7146-11eb-915d-4c5d5a81413c.png)

However, the inverter night time losses are allocated incorrectly:

![image](https://user-images.githubusercontent.com/5530592/108286422-47221f00-7146-11eb-8195-250102e88d76.png)

Figure out how to allocate the night time losses to the highest tier. I think this has something to do with the code around cmod_utility_rate5 line 1071, but should check with @sjanzou first.

**Comment by sjanzou** [comment]
@brtietz, does the inverter loss get added to the load appropriately before the utility rate compute module? What are the charges and tier breakdown with no load (and only inverter loss)? If this is just bookkeeping around line 1071, then the logic should check all the energy use at line 1123 against the upper bound for that tier and roll any excess to the next tier... so, definitely a bug but hard to tell if just bookkeeping or actual charge implications...

**Comment by cpaulgilman** [comment]
I just had a user support discussion that might be relevant to this regarding the effect of transformer losses (which scale with inverter size) on demand charges for months when the peak time step is at night. In this context, I just want to be sure that when we say "inverter loss" we mean the total nighttime loss.

[pv-inverter-transformer-losses-test.zip](https://github.com/NREL/ssc/files/6011510/pv-inverter-transformer-losses-test.zip)

**Comment by brtietz** [comment]
@sjanzou Based on my work for https://github.com/NREL/SAM/issues/370 (and soon to be work on https://github.com/NREL/SAM/issues/532) the inverter/transformer nighttime losses are negative numbers in gen, and not included in the load. My hunch is that this will affect the charges in addition to the bookkeeping. 

Good call on testing without load. Here's what happens to that same system:

![image](https://user-images.githubusercontent.com/5530592/108535812-f3741a80-7298-11eb-9cf4-1d9ca40fa6cc.png)

The tier structure is:
![image](https://user-images.githubusercontent.com/5530592/108535850-fec74600-7298-11eb-8252-92db119a2568.png)

and peak demand based on the nighttime losses alone is 0.339 kW, so that should be split 79.8 kWh in tier 2, and the rest in tier 6.

**Comment by brtietz** [comment]
This is closely related to https://github.com/NREL/ssc/issues/546, so move this to the fall release so all of the work happens on develop.

**Comment by brtietz** [comment]
The line numbers have shifted since this issue was first filed. Here's an updated permalink to save time in the future: https://github.com/NREL/ssc/blob/ec110c1a19e69e40d603c32655aab7341ff39519/ssc/cmod_utilityrate5.cpp#L1183

**Comment by sjanzou** [comment]
@brtietz, where is the test .sam file for the 

> @sjanzou Based on my work for [NREL/SAM#370](https://github.com/NREL/SAM/issues/370) (and soon to be work on [NREL/SAM#532](https://github.com/NREL/SAM/issues/532)) the inverter/transformer nighttime losses are negative numbers in gen, and not included in the load. My hunch is that this will affect the charges in addition to the bookkeeping.
> 
> Good call on testing without load. Here's what happens to that same system:
> 
> ![image](https://user-images.githubusercontent.com/5530592/108535812-f3741a80-7298-11eb-9cf4-1d9ca40fa6cc.png)
> 
> The tier structure is: ![image](https://user-images.githubusercontent.com/5530592/108535850-fec74600-7298-11eb-8252-92db119a2568.png)
> 
> and peak demand based on the nighttime losses alone is 0.339 kW, so that should be split 79.8 kWh in tier 2, and the rest in tier 6.

@brtietz, where is the .sam project file used to generate these tables? Thanks!

**Comment by brtietz** [comment]
@sjanzou The file used to generate the above is here:
[billing_demand_demo.zip](https://github.com/NREL/ssc/files/7590338/billing_demand_demo.zip) - the "ratchets off" case is probably the most useful for this issue.

However, for this issue I recommend testing with kWh tiers and nice round numbers. Here's an example for that: 
[evenly_distributed_tiers_test.zip](https://github.com/NREL/ssc/files/7590341/evenly_distributed_tiers_test.zip)

**Comment by sjanzou** [comment]
With pull request #673 , the inverter loss is moved to the highest tier that has not reached upper bound.
Test file 
[evenly_distributed_tiers_test_sj.zip](https://github.com/NREL/ssc/files/7613509/evenly_distributed_tiers_test_sj.zip)

Results before pull request
<img width="1232" alt="image" src="https://user-images.githubusercontent.com/6498311/143767294-01d6cd52-e5ea-44a4-858a-bd6446d3c1cf.png">


Results after pull request
<img width="1382" alt="image" src="https://user-images.githubusercontent.com/6498311/143767247-ca0980e8-74a7-4f2d-adb6-60b4679ad56c.png">
