### ISSUE TITLE
PV Module vs System Degradation

### ISSUE THREAD

**Issue by janinefreeman** [NREL/ssc#543]
There are a number of papers starting to address the fact that PV systems are subject to not only module degradation, but also degradation at the level of the entire system. The degradation input in SAM was originally intended to represent module degradation, but when it is applied on the AC side as it is when it is not run in lifetime mode, it more realistically is representing system degradation. Some papers have indicated that system degradation (which includes module degradation), is higher than the default values we've been using. Sort of a thorny issue, but one that we may want to investigate.

One reference here: [System-level performance and degradation of 21 GW-DC of utility-scale PV plants in the United States](https://emp.lbl.gov/publications/system-level-performance-and)

**Comment by natepreston** [comment]
@janinefreeman I am familiar with the reference you provided, as well as a number of other discussions on system level degradation. Generally, I have not seen from the literature much documentation of physical efficiency degradation mechanisms other than the traditional and well documented module degradation. I have been seeking further clarity on this topic, however I believe "System Degradation" over and above module degradation is primarily an issue of availability (e.g. increased frequency of faults, blown fuses, damaged cables, etc.). It would be helpful to keep DC module degradation separate from other blanket degradation mechanisms that might better be reflected in availability assumptions.
