### ISSUE TITLE
Fix Accounting for Inverter Operating Losses in LCOE/Gen

### ISSUE THREAD

**Issue by janinefreeman** [NREL/ssc#546]
Currently, inverter operating losses (day and nighttime) are subtracted off of `gen`, which is the energy used in the numerator of the LCOE. However, clarification from a solar/wind developer indicates that the energy required for inverter operating losses should actually be counted as an operating cost, and that energy should NOT be subtracted from `gen`. The operating cost can be calculated either at the PPA price (if no retail rate is specified), OR at the utility rate. (We'll still need to figure out what to do for behind-the-meter systems)

From the developer: "For the cash flow models she uses during the development phase to determine a PPA price to use in proposals for solar projects, she gets a single annual kWh estimate from her engineering team to account for total inverter consumption (day and nighttime), and then applies either the PPA price or a retail rate to estimate the operating cost. Because the kWh value is relatively small for solar projects, some utilities don't bother billing at the retail rate and treat it as negative generation, but other utilities do charge a retail rate. Retail rates are typically commercial rates with an energy charge and demand charge. On the wind side, site consumption is a larger fraction of the total system output, so this value has a bigger impact on the cash flow."

**Comment by brtietz** [comment]
Related issues: https://github.com/NREL/ssc/issues/539 https://github.com/NREL/SAM/issues/532

**Comment by brtietz** [comment]
Here's an interesting way to quantify this from patch 2:

This is the PV-Battery Single Owner default for patch 2. The battery only charges from PV in this case.

![image](https://user-images.githubusercontent.com/5530592/118018241-c887e880-b314-11eb-84a8-b94575cf20fe.png)

When I flip on the retail rate, the cost of the inverter night-time losses goes down (from $0.09 to $0.06), so the NPV goes up (which makes sense) but so does the LCOE (which doesn’t make sense):

![image](https://user-images.githubusercontent.com/5530592/118018265-cf166000-b314-11eb-8531-fe0f62ad2164.png)
 
The reason for the LCOE increase is increased OPEX, as discussed above.

When we've solved this bug, the decreased cost of night-time losses should be reflected in the LCOE and the NPV.
