### ISSUE TITLE
`batt_bank_replacement` indexed differently from `batt_replacement_schedule_percent`

### ISSUE THREAD

**Issue by dguittet** [NREL/ssc#601]
**Describe the bug**
`batt_bank_replacement` is length `analysis period` + 1 whereas `batt_replacement_schedule_percent` is length `analysis_period`

from cmod_singleowner.cpp:
```
cf.at(CF_battery_replacement_cost, i + 1) = batt_rep[i+1] * replacement_percent[i] * 0.01 *
                    cf.at(CF_battery_replacement_cost_schedule, i + 1);
```

**Expected behavior**
They should be indexed similarly. This inconsistently will lead to input errors.

**Comment by dguittet** [comment]
@brtietz Thanks for the context. I'm not sure how many other technology cmods report analysis_years + 1 length output arrays. I'll add it to discussion agenda for next week.

**Comment by brtietz** [comment]
SAM meeting 8/24: Paul found some similar annual arrays in Geothermal
