### ISSUE TITLE
FOM automated dispatch uses ppa_price_input even if irr target is selected

### ISSUE THREAD

**Issue by brtietz** [NREL/ssc#666]
The front of meter automated dispatch methods will use the ppa_price_input value from the defaults/GUI even if the financial models are run in IRR target mode:

![image](https://user-images.githubusercontent.com/5530592/142515038-537ba245-2330-40dc-a2f6-ae6cdc1a15ec.png)

The above code needs to reference ppa_soln_mode and come up with a surrogate PPA value, or the battery GUI pages need to warn the user that the value will be used.

**Comment by mjprilliman** [comment]
Steps to see issue: 
1. Open Standalone Battery - Single Owner case
2. On Revenue page, Select 'Specify PPA price', change PPA price to 0, then select 'Specify IRR target'
3. On Dispatch page, select Automated dispatch
4. Simulate
5. Results have NaN battery energy charge and roundtrip efficiency

[Automated_dispatch_PPA.zip](https://github.com/NREL/ssc/files/7566799/Automated_dispatch_PPA.zip)

**Comment by brtietz** [comment]
Fixed with the above pull requests
