### ISSUE TITLE
DC Connected battery and gid outages

### ISSUE THREAD

**Issue by sjanzou** [NREL/ssc#722]
Run parametrics in attached SAM project file - one case dc connected and one case ac connected.
No annual output shown for dc case

base case has undersized battery and shows same system output in heat map on summary page but no annual output.

I can’t tell what’s meeting the critical load at night. The inverter efficiency appears to drop to zero at night, and with a two hour battery there shouldn’t be enough power to meet the critical load anyway.
Changing the parameters such as inverter efficiency cutoff and re-sizing the system doesn’t fix the problem.
 
Based on that, the issue is either in the inverter model or in the post-battery loss accounting for DC connected systems. 

[MiniGrid.zip](https://github.com/NREL/ssc/files/7892353/MiniGrid.zip)

![image](https://user-images.githubusercontent.com/6498311/150018667-e2253748-bb9c-41ec-abee-f7e9de183b63.png)

![image](https://user-images.githubusercontent.com/6498311/150018735-53c19d48-34e3-4446-8229-6033cccb6d17.png)

**Comment by brtietz** [comment]
Fixed in #725
