### ISSUE TITLE
Wind Resource Probability Distribution Bug

### ISSUE THREAD

**Issue by dguittet** [NREL/ssc#724]
The Wind Resource Probability Distribution option produces annual energy results that are much, much lower than expected.

**Comment by mjprilliman** [comment]
@dguittet Could this be related to the turbine design parameter issue in https://github.com/NREL/SAM/issues/877? The probability distribution option is currently passing a value of 0 for the elevation to the wind powercurve calculations each time. Changing that behavior to assume elevation = hub height (with optional elevation above sea level set to 0) lead to the following before and after in annual energy. This only applies if you are seeing these results for user-defined turbines. 

Elevation = 0
![image](https://user-images.githubusercontent.com/54449384/151626146-5a4daec7-8b26-42c8-9e27-e31eb5e374ca.png)


Elevation = 80 m (hub height)
![image](https://user-images.githubusercontent.com/54449384/151626186-c3ed92d4-306a-44d5-a7df-f7c5e98cc2a8.png)
