### ISSUE TITLE
Update multiple-MPPT inverter model

### ISSUE THREAD

**Issue by janinefreeman** [NREL/ssc#771]
Cliff Hansen has an updated/validated algorithm for how to adapt the Sandia inverter model for multiple MPPT inverters. Code implementation in pvlib (sandia_multi) is here: https://github.com/pvlib/pvlib-python/blob/master/pvlib/inverter.py

**Comment by cwhanse** [comment]
Paper available [here](https://www.researchgate.net/publication/361114989_Modeling_Efficiency_of_Inverters_with_Multiple_Inputs)
