### ISSUE TITLE
Inverter Model Typo

### ISSUE THREAD

**Issue by janinefreeman** [NREL/ssc#841]
The Sandia inverter model implementation in SAM appears to have a typo with one of the coefficients, see description here: https://sam.nrel.gov/forum/forum-general/3844 . Just examined documentation and confirmed issue.

**Comment by cwhanse** [comment]
I concur, it's an error - line 424 should be using "C * (Pdc[m] - B) * (Pdc[m] - B)" not "C0 * ..."
