### ISSUE TITLE
(Mis-)handling of missing TMY3/EPW values

### ISSUE THREAD

**Issue by bje-** [NREL/ssc#85]
The EPW and TMY3 file formats specify special values for missing data, but `lib_weatherfile.cpp`  does not appear to observe these. It treats these as literal values,  giving haphazard results without any warning. It would be useful for SAM  to either do sensible interpolation or at least notify the user of any  missing data values it is using.

**Comment by dguittet** [comment]
Thanks for pointing this out!

I have added missing value checks for EPW files. For TMY3 files, the user manual (https://www.nrel.gov/docs/fy08osti/43156.pdf) specifies that missing irradiance and meteorological values are filled in by a protocol prior to release so for the fields SAM uses, TMY3 files should have no missing values.
