### ISSUE TITLE
Change array inputs that are specified as single number to single value array inputs in ssc precheck

### ISSUE THREAD

**Issue by sjanzou** [NREL/ssc#906]
Per 10/25/2022 meeting and SAM issue https://github.com/NREL/SAM/issues/1038

Change all ssc array inputs that are passed into ssc as single number to a single value array and log message.

**Comment by brtietz** [comment]
In addition to the SSC changes proposed here, we will need to update PySAM, the function here fails when provided a number https://github.com/NREL/pysam/blob/master/files/PySSC.py#L70

Generally all of these functions could use a try-except which gives the name of the variable when there is an error, but that's a separate issue.
