### ISSUE TITLE
query in shared/lib_util.cpp

### ISSUE THREAD

**Issue by bje-** [NREL/ssc#94]
In `shared/lib_utill.cpp`, we have this in `util::format`:

	do
	{
		va_list argptr_copy;
		va_copy( argptr_copy, arglist );
		ret = util::format_vn(buffer,size-1,fmt,argptr_copy);
		va_end( argptr_copy );

		if (ret == 0)
		{
			delete [] buffer;
			size *= 2;
			buffer = new char[size];
			if (!buffer)
				return "";
		}
		
	}
	while (ret < 0);

`ret` is of type `size_t` which is an unsigned type and so `ret` can never be negative. This `do`/`while` loop can only ever execute once. Is this what was intended?

**Comment by nickdiorio** [comment]
I honestly don't know what was intended here.  Having been through this in depth, this function and the call to `util::format_vn` appears to be a needlessly complex way to make it shorter to call `sprintf`.  As for the do-while loop, you are correct that it can never get hit.  I've written some tests for this, and it appears to behave as expected, so I'm about to check in a change that removes the do-while loop and adds a few comments.
