### ISSUE TITLE
query: variables assigned to themselves

### ISSUE THREAD

**Issue by bje-** [NREL/ssc#96]
clang reports the following warnings when compiling tcs:

    ../tcs/sam_pf_dish_parasitic_type298.cpp:512:16: warning: explicitly assigning value of variable of type 'double' to itself [-Wself-assign]
                                            fan_speed =  fan_speed;
    ../tcs/sam_pf_dish_parasitic_type298.cpp:799:10: warning: explicitly assigning value of variable of type 'double' to itself [-Wself-assign]
                            P_fan = P_fan;
    ../tcs/sam_pf_dish_parasitic_type298.cpp:808:16: warning: explicitly assigning value of variable of type 'double' to itself [-Wself-assign]
                            P_tower_fan = P_tower_fan;
    ../tcs/storage_hx.cpp:100:18: warning: assigning field to itself [-Wself-assign-field]
            m_max_q_htr_hot = m_max_q_htr_hot;
    ../tcs/csp_solver_pt_sf_perf_interp.cpp:373:16: warning: assigning field to itself [-Wself-assign-field]
            m_v_wind_prev = m_v_wind_prev;

What was intended in each case?

**Comment by nickdiorio** [comment]
It's difficult for me to see how these are anything but trivial assignments.  I suspect they are mostly for commenting purposes.  Feel free to remove in any subsequent pull requests, thanks!

**Comment by bje-** [comment]
Thanks. Inspecting the code in storage_hx.cpp shows what the real intent was -- to set a class member based on a function argument just like the 'cold' case in the line above. See the forthcoming PR for the details.
