### ISSUE TITLE
3D Shading Bug

### ISSUE THREAD

**Issue by nickdiorio** [NREL/ssc#97]
There may be a new bug in the 3D shade calculator that wasn’t there in SAM 2017.1.17 r4. I think it is caused by objects below the active surface, even though they are not “touching.” For the attached shading scene, the time series shading factors generated by the calculator for PVWatts are:
 
In SAM 2017.9.5 – this looks wrong:
![shading_wrong](https://user-images.githubusercontent.com/5658281/34019931-710b23de-e0ee-11e7-8c83-03eff9aaf638.png)

In SAM 2017.1.17 - this looks reasonable
![shading_right](https://user-images.githubusercontent.com/5658281/34019938-7ff05996-e0ee-11e7-84a9-8925a5294914.png)

**Comment by cpaulgilman** [comment]
Fixed in SAM repo.
