### ISSUE TITLE
Lifetime battery degradation resets to 100% for small augmentation

### ISSUE THREAD

**Issue by brtietz** [NREL/ssc#974]
**Describe the bug**
Battery augmentation causes the lifetime component of the cycle life model to reset degradation to 100%, regardless of the amount of augmentation. This can lead to long periods with no degradation, which does not match expectations of real world performance.

**To Reproduce**
1. Run the attached SAM file: 
[lfp-lifetime-test-btm.zip](https://github.com/NREL/ssc/files/10483323/lfp-lifetime-test-btm.zip)

2. See lack of degradation after augmentation

**Expected behavior**
TODO: define expected behavior

**Screenshots**
![image](https://user-images.githubusercontent.com/5530592/214140815-02f286c9-a4e4-49e9-99ac-c8972e5452bd.png)

**Desktop (please complete the following information):**
 - Version 2022.11.21, maybe others

**Comment by dguittet** [comment]
from conversations with Paul, simple ways to do this are:

For a 10 kwh battery that has lost 70% of its capacity (70% cycle and 70% calendar):
 
- If the augmentation is for 3 kwh, then the battery should be back to 10kwh of capacity (no calendar or cycling degradation)
- If the augmentation is for 1 kwh, then the battery should be back to ~8 kwh of capacity (figure out how to get both calendar and cycling degradation back to ~80%)
 
There would be two caveats with this approach:
- Degradation tends to be faster in new cells, so this overestimates degradation rate, but…
- This does not account for safety/reliability risks of having very low health cells (higher sudden failure rate at low health)
