### ISSUE TITLE
Bug with certain PV radiation input combinations

### ISSUE THREAD

**Issue by nickdiorio** [NREL/ssc#98]
There is bug that affects all lifetime pvsamv1 simulations that use irradiance data other than (DNI and DHI) or (DNI and GHI) on the Solar resource page.  This has been fixed and will be released in an upcoming patch.

**Comment by cpaulgilman** [comment]
Closed in #94655afb927bcc44011ba1371406bd2654af3c49

**Comment by nickdiorio** [comment]
94655afb927bcc44011ba1371406bd2654af3c49

**Comment by janinefreeman** [comment]
Caused SAM to crash when self-shading was enabled. Fixed.
